USE CONTROL_INVENTARIO_BD;
GO

-- Agregando las columnas que faltan a la tabla HISTORIAL_ACTIVIDAD

ALTER TABLE HISTORIAL_ACTIVIDAD 
ADD modulo VARCHAR(50) NULL;

ALTER TABLE HISTORIAL_ACTIVIDAD 
ADD entidad_afectada VARCHAR(50) NULL;

ALTER TABLE HISTORIAL_ACTIVIDAD 
ADD id_entidad BIGINT NULL;

ALTER TABLE HISTORIAL_ACTIVIDAD 
ADD ip_direccion VARCHAR(45) NULL;

ALTER TABLE HISTORIAL_ACTIVIDAD 
ADD detalles_cambios VARCHAR(MAX) NULL; -- Usamos MAX en lugar de TEXT que es antiguo

GO